name: Bun Vite CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
   
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        
      - name: Install Depedencies
        run: bun i

      - name: Type Checking
        run: bun type-check

  deploy:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
     
      - name: Deploy repo
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.ID_CLOUDHOST_SECRET }}
          port: 22
          script: |
            cd ~/projects/bun-vite
            git pull origin main
            bun install
            bun run build
            pm2 restart bun-vite
           
