name: Bun Vite CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
   
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        
      - name: Install Depedencies
        run: bun i

      - name: Type Checking
        run: bun type-check

      - name: Building the project
        run: bun run build

  deploy:
    runs-on: ubuntu-latest
     steps:
      - name: Deploy Using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.ID_CLOUDHOST_SECRET }}
          target: /projects/bun-vite
          script: |
            git pull origin main
            pm2 restart bun-vite
           
